framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
        routing:
            App\Message\ExampleMessage: async
            App\Message\DispatchNotificationMessage: async
            App\Message\DispatchWebhookEventMessage: async
            App\Message\ChatbotQueryMessage: async
            App\Message\CreateShipmentMessage: async
            App\Message\SyncShipmentTrackingMessage: async
